import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const list = readFileSync(new URL('FacilityListPage.tsx', import.meta.url), 'utf8')
const drawer = readFileSync(new URL('components/FacilityContentDrawer.tsx', import.meta.url), 'utf8')
const api = readFileSync(new URL('../../api/scenic.ts', import.meta.url), 'utf8')

assert.match(api, /spotCode/)
assert.match(api, /shortDescription/)
assert.match(api, /locationDescription/)
assert.match(api, /mapVisible/)
assert.match(api, /export type ScenicFacilityContent/)
assert.match(api, /architectureLandscapeParams/)
assert.match(api, /culturalConnotation/)
assert.match(api, /visitorNotes/)
assert.match(api, /getScenicFacilityContent/)
assert.match(api, /saveScenicFacilityContent/)
assert.match(api, /getScenicFacilityVoiceScripts/)
assert.match(api, /\/api\/admin\/scenic\/facilities\/\$\{id\}\/voice-scripts/)
assert.match(api, /getScenicFacilityVoiceScriptCandidates/)
assert.match(api, /\/api\/admin\/scenic\/facilities\/\$\{id\}\/voice-script-candidates/)

assert.match(list, /内容配置/)
assert.match(list, /FacilityContentDrawer/)
assert.match(drawer, /文化资料/)
assert.match(drawer, /口播语音/)
assert.match(drawer, /直播配置/)
assert.match(drawer, /textArea\('architectureLandscapeParams'/)
assert.match(drawer, /textArea\('coreFunction'/)
assert.match(drawer, /textArea\('culturalConnotation'/)
assert.match(drawer, /textArea\('detailedIntroduction'/)
assert.match(drawer, /textArea\('highlights'/)
assert.match(drawer, /textArea\('performanceOpenInfo'/)
assert.match(drawer, /textArea\('visitorNotes'/)
assert.match(drawer, /name="audioEnabled"/)
assert.match(drawer, /name="boundVoiceScriptId"/)
assert.match(drawer, /synthesizeVoiceScriptRecord/)
assert.match(drawer, /publishVoiceScriptRecord/)
assert.match(drawer, /合成试听/)
assert.match(drawer, /发布并绑定/)
assert.match(drawer, /audio controls/)
assert.match(drawer, /audioStatus/)
assert.match(drawer, /speechRate/)
assert.match(drawer, /Promise\.allSettled/)
assert.match(drawer, /数字人模型加载失败，直播配置暂不可用/)
assert.doesNotMatch(drawer, /setScripts\(voiceScripts\)\s+setDigitalHumanModelLoadError\(''\)/)
assert.match(drawer, /if \(isFormValidationError\(error\)\) return/)
assert.match(drawer, /selectedScript\.status !== 'draft'/)
assert.match(drawer, /只有草稿版本允许直接合成/)
assert.match(drawer, /当前版本已归档或发布，如需调整音色或文本，请先在口播管理中回滚为新草稿。/)
assert.match(drawer, /name="liveEnabled"/)
assert.match(drawer, /name="liveSourceType"/)
assert.match(api, /liveDigitalHumanModelId/)
assert.match(drawer, /modelEmotionApi\.getModels\(\)/)
assert.match(drawer, /name="liveDigitalHumanModelId"/)
assert.match(drawer, /开启直播后必须选择直播数字人/)
assert.match(drawer, /uploadScenicLiveVideo/)
assert.match(drawer, /Form\.useWatch\('liveVideoUrl'/)
assert.match(drawer, /<video[\s\S]*controls[\s\S]*src=\{liveVideoUrl\}/)
assert.match(drawer, /视频预览/)
assert.match(drawer, /navigator\.mediaDevices\.getUserMedia/)

console.log('official facility content configuration contract passed')
