import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const list = readFileSync(new URL('FacilityListPage.tsx', import.meta.url), 'utf8')
const drawer = readFileSync(new URL('components/FacilityContentDrawer.tsx', import.meta.url), 'utf8')
const api = readFileSync(new URL('../../api/scenic.ts', import.meta.url), 'utf8')

assert.match(api, /spotCode/)
assert.match(api, /shortDescription/)
assert.match(api, /locationDescription/)
assert.match(api, /mapVisible/)
assert.match(api, /export type ScenicFacilityContent/)
assert.match(api, /architectureLandscapeParams/)
assert.match(api, /culturalConnotation/)
assert.match(api, /visitorNotes/)
assert.match(api, /getScenicFacilityContent/)
assert.match(api, /saveScenicFacilityContent/)
assert.match(api, /getScenicFacilityVoiceScripts/)

assert.match(list, /内容配置/)
assert.match(list, /FacilityContentDrawer/)
assert.match(drawer, /文化资料/)
assert.match(drawer, /口播语音/)
assert.match(drawer, /直播配置/)
assert.match(drawer, /textArea\('architectureLandscapeParams'/)
assert.match(drawer, /textArea\('coreFunction'/)
assert.match(drawer, /textArea\('culturalConnotation'/)
assert.match(drawer, /textArea\('detailedIntroduction'/)
assert.match(drawer, /textArea\('highlights'/)
assert.match(drawer, /textArea\('performanceOpenInfo'/)
assert.match(drawer, /textArea\('visitorNotes'/)
assert.match(drawer, /name="audioEnabled"/)
assert.match(drawer, /name="boundVoiceScriptId"/)
assert.match(drawer, /name="liveEnabled"/)
assert.match(drawer, /name="liveSourceType"/)
assert.match(drawer, /uploadScenicLiveVideo/)
assert.match(drawer, /navigator\.mediaDevices\.getUserMedia/)

console.log('official facility content configuration contract passed')
