import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const page = readFileSync(new URL('ScenicStructuredPage.tsx', import.meta.url), 'utf8')
const api = readFileSync(new URL('../../api/scenicStructured.ts', import.meta.url), 'utf8')

assert.match(api, /audio_enabled: boolean/)
assert.match(api, /live_enabled: boolean/)
assert.match(api, /default_experience: 'audio' \| 'live' \| null/)
assert.match(api, /bound_voice_script_id: number \| null/)
assert.match(api, /live_source_type: 'video' \| 'stream' \| 'camera' \| null/)
assert.match(api, /live_video_url: string/)
assert.match(api, /live_stream_url: string/)
assert.match(api, /camera_stream_key: string/)
assert.match(api, /getPublishedVoiceScripts/)
assert.match(api, /\/api\/admin\/voice-scripts\/published/)
assert.match(api, /params: \{ spotId \}/)
assert.match(api, /uploadScenicLiveVideo\(file: File\)/)
assert.match(api, /formData\.append\('file', file\)/)
assert.match(api, /\/api\/admin\/scenic-structured\/media\/upload/)
assert.match(api, /'Content-Type': 'multipart\/form-data'/)

assert.match(page, /游客呈现/)
assert.match(page, /name="audio_enabled"/)
assert.match(page, /name="live_enabled"/)
assert.match(page, /getPublishedVoiceScripts\(spotId\)/)
assert.match(page, /仅显示该景点已发布且音频可用的口播/)
assert.match(page, /name="bound_voice_script_id"/)
assert.match(page, /启用语音后必须绑定一条可用口播/)

assert.match(page, /name="live_source_type"/)
assert.match(page, /上传视频/)
assert.match(page, /播放流/)
assert.match(page, /摄像头推流/)
assert.match(page, /liveSourceType === 'video'/)
assert.match(page, /name="live_video_url"/)
assert.match(page, /accept="video\/\*"/)
assert.match(page, /uploadScenicLiveVideo\(file as File\)/)
assert.match(page, /form\.setFieldValue\('live_video_url', result\.url\)/)
assert.match(page, /上传视频文件/)
assert.match(page, /也可以手工填写或修改视频地址/)
assert.match(page, /liveSourceType === 'stream'/)
assert.match(page, /name="live_stream_url"/)
assert.match(page, /liveSourceType === 'camera'/)
assert.match(page, /name="camera_stream_key"/)
assert.match(page, /摄像头推流必须配置推流通道/)

assert.match(page, /name="default_experience"/)
assert.match(page, /默认入口必须是已启用的体验/)
assert.match(page, /直播不可用时将自动回退到语音讲解/)

assert.match(page, /navigator\.mediaDevices\.getUserMedia/)
assert.match(page, /getTracks\(\)\.forEach\(\(track\) => track\.stop\(\)\)/)
assert.match(page, /仅完成权限检测，真实直播仍需配置 WebRTC\/直播网关推流通道/)

console.log('scenic structured visitor presentation contract passed')
