import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const layout = readFileSync(new URL('./AdminLayout.tsx', import.meta.url), 'utf8')
const css = readFileSync(new URL('../App.css', import.meta.url), 'utf8')
const dashboard = readFileSync(new URL('./OperationsDashboardPage.tsx', import.meta.url), 'utf8')
const feedback = readFileSync(new URL('./FeedbackManagementPage.tsx', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../components/AdminSidebar.tsx', import.meta.url), 'utf8')
const modelManual = readFileSync(new URL('./settings/ModelManualPage.tsx', import.meta.url), 'utf8')
const liveBroadcast = readFileSync(new URL('./LiveBroadcastManagementPage.tsx', import.meta.url), 'utf8')
const liveBroadcastApi = readFileSync(new URL('../api/liveBroadcast.ts', import.meta.url), 'utf8')

assert.match(layout, /OperationsDashboardPage/)
assert.match(layout, /FeedbackManagementPage/)
assert.match(css, /@media\s*\(max-width:\s*1024px\)/)
assert.match(css, /@media\s*\(max-width:\s*768px\)/)
assert.match(dashboard, /getOperationsOverview/)
assert.match(dashboard, /echarts\.init/)
assert.match(dashboard, /function MetricsRegion/)
assert.match(dashboard, /function RankingsRegion/)
assert.match(dashboard, /function HealthRegion/)
assert.match(dashboard, /RegionError/)
assert.match(dashboard, /const region = useOverviewRegion\(\)/, 'dashboard must create one shared overview state')
assert.match(dashboard, /<MetricsRegion region=\{region\}[^]*<RankingsRegion region=\{region\}[^]*<HealthRegion region=\{region\}/, 'dashboard regions must consume the shared overview state')
assert.match(dashboard, /\['healthy', 'up', 'ok'\]/)
assert.match(sidebar, /\(max-width: 768px\)/)
assert.match(sidebar, /matchMedia\(MOBILE_NAV_QUERY\)/)
assert.match(feedback, /updateFeedback/)
assert.match(feedback, /Drawer/)
assert.match(modelManual, /handleTestConnection[\s\S]*?try\s*\{[\s\S]*?finally\s*\{\s*setTestingConnection\(false\)/, 'provider connection testing must always reset loading state')
assert.match(modelManual, /handleTestModel[\s\S]*?try\s*\{[\s\S]*?finally\s*\{\s*setTestingModelKey\(null\)/, 'model testing must always reset loading state')
assert.match(sidebar, /key:\s*'live-broadcast'[\s\S]*?label:\s*'数字人直播'/)
assert.match(layout, /LiveBroadcastManagementPage/)
assert.match(layout, /'live-broadcast':\s*'\/admin\/live-broadcast'/)
assert.match(layout, /case\s*'live-broadcast':[\s\S]*?<LiveBroadcastManagementPage\s*\/>/)
assert.match(liveBroadcast, /listLiveItems/)
assert.match(liveBroadcast, /publishLiveBroadcast/)
assert.match(liveBroadcast, /const \[mutationPending, setMutationPending\] = useState\(false\)/)
assert.match(liveBroadcast, /runDraftMutation/)
assert.match(liveBroadcast, /await listLiveItems\(\)/, 'failed mutations must recover from the server, not a stale closure')
assert.doesNotMatch(liveBroadcast, /catch[^]*setItems\(items\)/, 'failed reorder must not restore a stale items closure')
assert.match(liveBroadcast, /disabled=\{mutationPending\s*\|\|/)
assert.match(liveBroadcast, /loading=\{publishing\}/)
assert.match(liveBroadcast, /className="live-broadcast-management-page"/)
assert.match(css, /\.live-broadcast-management-page\s*\{[^}]*min-height:\s*0;[^}]*overflow-y:\s*auto;[^}]*overscroll-behavior:\s*contain;/)
assert.match(sidebar, /function getMenuItems\(role:[^]*role\s*===\s*'ADMIN'[^]*menuItems\.filter\(\(item\) => item\?\.key !== 'live-broadcast'\)/)
assert.match(sidebar, /items=\{getMenuItems\(role\)\}/)
assert.match(liveBroadcastApi, /BASE_PATH\s*=\s*'\/api\/admin\/live-broadcast'/)
assert.match(liveBroadcastApi, /`\$\{BASE_PATH\}\/items`/)
assert.match(liveBroadcastApi, /`\$\{BASE_PATH\}\/items\/reorder`/)
assert.match(liveBroadcastApi, /`\$\{BASE_PATH\}\/publish`/)
assert.match(liveBroadcastApi, /`\$\{BASE_PATH\}\/published`/)

console.log('admin upgrade structure verified')
