import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const layout = readFileSync(new URL('./AdminLayout.tsx', import.meta.url), 'utf8')
const css = readFileSync(new URL('../App.css', import.meta.url), 'utf8')
const dashboard = readFileSync(new URL('./OperationsDashboardPage.tsx', import.meta.url), 'utf8')
const feedback = readFileSync(new URL('./FeedbackManagementPage.tsx', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../components/AdminSidebar.tsx', import.meta.url), 'utf8')
const modelManual = readFileSync(new URL('./settings/ModelManualPage.tsx', import.meta.url), 'utf8')

assert.match(layout, /OperationsDashboardPage/)
assert.match(layout, /FeedbackManagementPage/)
assert.match(css, /@media\s*\(max-width:\s*1024px\)/)
assert.match(css, /@media\s*\(max-width:\s*768px\)/)
assert.match(dashboard, /getOperationsOverview/)
assert.match(dashboard, /echarts\.init/)
assert.match(dashboard, /function MetricsRegion/)
assert.match(dashboard, /function RankingsRegion/)
assert.match(dashboard, /function HealthRegion/)
assert.match(dashboard, /RegionError/)
assert.match(dashboard, /const region = useOverviewRegion\(\)/, 'dashboard must create one shared overview state')
assert.match(dashboard, /<MetricsRegion region=\{region\}[^]*<RankingsRegion region=\{region\}[^]*<HealthRegion region=\{region\}/, 'dashboard regions must consume the shared overview state')
assert.match(dashboard, /\['healthy', 'up', 'ok'\]/)
assert.match(sidebar, /\(max-width: 768px\)/)
assert.match(sidebar, /matchMedia\(MOBILE_NAV_QUERY\)/)
assert.match(feedback, /updateFeedback/)
assert.match(feedback, /Drawer/)
assert.match(modelManual, /handleTestConnection[\s\S]*?try\s*\{[\s\S]*?finally\s*\{\s*setTestingConnection\(false\)/, 'provider connection testing must always reset loading state')
assert.match(modelManual, /handleTestModel[\s\S]*?try\s*\{[\s\S]*?finally\s*\{\s*setTestingModelKey\(null\)/, 'model testing must always reset loading state')

console.log('admin upgrade structure verified')
