app.backend-base-url=http://127.0.0.1:8080
app.ai-service-url=http://127.0.0.1:18755

ai.service-url=${app.ai-service-url}

tts.base-url=${app.backend-base-url}
tts.edge-service-url=${app.ai-service-url}
