import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const page = readFileSync(join(root, 'DigitalHumanPage.tsx'), 'utf8')

assert.match(page, /getMobileLiveComments\(messages, mobileRuntimeComment\)/)
assert.match(page, /className="digital-human-mobile-live"/)
assert.match(page, /className="digital-mobile-comment-feed"/)
assert.match(page, /const livePageRef = useRef<HTMLElement \| null>\(null\)/)
assert.match(page, /ref=\{livePageRef\}[\s\S]*className="live2d-page live2d-page--presentation"/)
assert.match(page, /const viewport = window\.visualViewport/)
assert.match(page, /viewport\?\.height \?\? window\.innerHeight/)
assert.match(page, /viewport\?\.offsetTop \?\? 0/)
assert.match(page, /Math\.max\(0, window\.innerHeight - viewportHeight - viewportOffsetTop\)/)
assert.match(page, /setProperty\('--digital-mobile-viewport-height', `\$\{viewportHeight\}px`\)/)
assert.match(page, /setProperty\('--digital-mobile-viewport-offset-top', `\$\{viewportOffsetTop\}px`\)/)
assert.match(page, /setProperty\('--digital-mobile-viewport-bottom-inset', `\$\{viewportBottomInset\}px`\)/)
assert.match(page, /viewport\?\.addEventListener\('resize', syncMobileViewport\)/)
assert.match(page, /viewport\?\.addEventListener\('scroll', syncMobileViewport\)/)
assert.match(page, /window\.addEventListener\('resize', syncMobileViewport\)/)
assert.match(page, /viewport\?\.removeEventListener\('resize', syncMobileViewport\)/)
assert.match(page, /viewport\?\.removeEventListener\('scroll', syncMobileViewport\)/)
assert.match(page, /window\.removeEventListener\('resize', syncMobileViewport\)/)
assert.match(page, /className="sr-only"[\s\S]*aria-live="polite"/)
assert.match(page, /onend:\s*\(\(\) => void\) \| null/)
assert.match(page, /recognition\.onend = \(\) =>/)
assert.match(page, /recognitionRef\.current !== recognition/)
assert.match(page, /recognition\.onerror = \(\) => \{[\s\S]*hadRecognitionError = true[\s\S]*setRuntimeState\('error'\)/)
assert.match(page, /if \(!hadRecognitionError\)[\s\S]*setRuntimeState\('idle'\)/)
assert.match(page, /getMobileLiveComments\(messages, mobileRuntimeComment\)/)
assert.match(page, /\['loading', 'listening', 'thinking', 'error'\]\.includes\(runtimeState\)/)
assert.match(page, /const \[mobileLiveAnnouncement, setMobileLiveAnnouncement\] = useState\(''\)/)
assert.match(page, /aria-live="polite" aria-atomic="true">\s*\{mobileLiveAnnouncement\}/)
assert.doesNotMatch(page, /aria-live="polite" aria-atomic="true">\s*\{messages\.at\(-1\)\?\.content\}/)
assert.match(page, /placeholder="问问灵灵…"/)
assert.match(page, /startVoiceQuestion/)
assert.match(page, /role="dialog"[\s\S]*aria-modal="true"/)
assert.match(page, /event\.key === 'Escape'/)
assert.match(page, /mobileHistoryReturnFocusRef = useRef<HTMLElement \| null>\(null\)/)
assert.match(page, /mobileHistoryReturnFocusRef\.current = trigger/)
assert.match(page, /openMobileHistory\(message\.id, event\.currentTarget\)/)
assert.match(page, /openMobileHistory\(undefined, event\.currentTarget\)/)
assert.match(page, /mobileHistoryReturnFocusRef\.current\?\.focus\(\)/)
assert.doesNotMatch(page, /historyTriggerRef/)
assert.match(page, /settingsTriggerRef\.current\?\.focus\(\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*a\[href\]:not\(\[tabindex="-1"\]\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*button:not\(:disabled\):not\(\[tabindex="-1"\]\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*input:not\(:disabled\):not\(\[tabindex="-1"\]\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*select:not\(:disabled\):not\(\[tabindex="-1"\]\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*textarea:not\(:disabled\):not\(\[tabindex="-1"\]\)/)
assert.match(page, /querySelector<HTMLElement>\(MOBILE_DIALOG_FOCUSABLE_SELECTOR\)/)
assert.match(page, /querySelectorAll<HTMLElement>\(MOBILE_DIALOG_FOCUSABLE_SELECTOR\)/)
assert.match(page, /matchMedia\('\(min-width: 769px\)'\)[\s\S]*messagesEndRef\.current\?\.scrollIntoView/)
assert.match(
  page,
  /type MouseEvent as ReactMouseEvent[\s\S]*function handleMobileQuickQuestion\(event: ReactMouseEvent<HTMLButtonElement>\)[\s\S]*sendQuestion\(event\.currentTarget\.dataset\.question \?\? ''\)/,
  'quick questions must enter the existing session through an event handler outside the render-time map callback',
)
assert.match(page, /MOBILE_LIVE_QUICK_QUESTIONS\.map[\s\S]*data-question=\{item\.question\}[\s\S]*onClick=\{handleMobileQuickQuestion\}/)
assert.match(page, /className="digital-human-chat"/, 'desktop chat remains rendered')
console.log('mobile digital-human live interaction contract passed')
