import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const page = readFileSync(join(root, 'DigitalHumanPage.tsx'), 'utf8')
const styles = readFileSync(join(root, 'DigitalHumanPage.css'), 'utf8')
const mobileLive = readFileSync(join(root, '../digitalHuman/mobileLive.ts'), 'utf8')

assert.match(page, /getMobileLiveComments\(messages, mobileRuntimeComment\)/)
assert.match(page, /className="digital-human-mobile-live"/)
assert.match(page, /className="digital-mobile-comment-feed"/)
assert.match(page, /const livePageRef = useRef<HTMLElement \| null>\(null\)/)
assert.match(page, /ref=\{livePageRef\}[\s\S]*className="live2d-page live2d-page--presentation"/)
assert.match(page, /const viewport = window\.visualViewport/)
assert.match(page, /viewport\?\.height \?\? window\.innerHeight/)
assert.match(page, /viewport\?\.offsetTop \?\? 0/)
assert.match(page, /Math\.max\(0, window\.innerHeight - viewportHeight - viewportOffsetTop\)/)
assert.match(page, /setProperty\('--digital-mobile-viewport-height', `\$\{viewportHeight\}px`\)/)
assert.match(page, /setProperty\('--digital-mobile-viewport-offset-top', `\$\{viewportOffsetTop\}px`\)/)
assert.match(page, /setProperty\('--digital-mobile-viewport-bottom-inset', `\$\{viewportBottomInset\}px`\)/)
assert.match(page, /viewport\?\.addEventListener\('resize', syncMobileViewport\)/)
assert.match(page, /viewport\?\.addEventListener\('scroll', syncMobileViewport\)/)
assert.match(page, /window\.addEventListener\('resize', syncMobileViewport\)/)
assert.match(page, /viewport\?\.removeEventListener\('resize', syncMobileViewport\)/)
assert.match(page, /viewport\?\.removeEventListener\('scroll', syncMobileViewport\)/)
assert.match(page, /window\.removeEventListener\('resize', syncMobileViewport\)/)
assert.match(page, /className="sr-only"[\s\S]*aria-live="polite"/)
assert.match(page, /onend:\s*\(\(\) => void\) \| null/)
assert.match(page, /recognition\.onend = \(\) =>/)
assert.match(page, /recognitionRef\.current !== recognition/)
assert.match(
  page,
  /async function sendQuestion\(questionInput: string\) \{\s*invalidateSpeechRecognition\(recognitionRef, recognitionGenerationRef\)/,
  'every send path must invalidate an active speech recognition before changing question state',
)
assert.match(page, /recognition\.onerror = \(\) => \{[\s\S]*hadRecognitionError = true[\s\S]*setRuntimeState\('error'\)/)
assert.match(page, /if \(!hadRecognitionError\)[\s\S]*setRuntimeState\('idle'\)/)
assert.match(page, /getMobileLiveComments\(messages, mobileRuntimeComment\)/)
assert.match(page, /\['loading', 'listening', 'thinking', 'error'\]\.includes\(runtimeState\)/)
assert.match(page, /const \[mobileLiveAnnouncement, setMobileLiveAnnouncement\] = useState\(''\)/)
assert.match(page, /aria-live="polite" aria-atomic="true">\s*\{mobileLiveAnnouncement\}/)
assert.doesNotMatch(page, /aria-live="polite" aria-atomic="true">\s*\{messages\.at\(-1\)\?\.content\}/)
assert.match(page, /placeholder="问问灵灵…"/)
assert.match(page, /startVoiceQuestion/)
assert.match(page, /role="dialog"[\s\S]*aria-modal="true"/)
assert.match(page, /event\.key === 'Escape'/)
assert.match(page, /mobileHistoryReturnFocusRef = useRef<HTMLElement \| null>\(null\)/)
assert.match(page, /mobileHistoryReturnFocusRef\.current = trigger/)
assert.match(page, /openMobileHistory\(message\.id, event\.currentTarget\)/)
assert.match(page, /mobileHistoryReturnFocusRef\.current\?\.focus\(\)/)
assert.doesNotMatch(page, /historyTriggerRef/)
assert.match(page, /settingsTriggerRef\.current\?\.focus\(\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*a\[href\]:not\(\[tabindex="-1"\]\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*button:not\(:disabled\):not\(\[tabindex="-1"\]\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*input:not\(:disabled\):not\(\[tabindex="-1"\]\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*select:not\(:disabled\):not\(\[tabindex="-1"\]\)/)
assert.match(page, /MOBILE_DIALOG_FOCUSABLE_SELECTOR[\s\S]*textarea:not\(:disabled\):not\(\[tabindex="-1"\]\)/)
assert.match(page, /querySelector<HTMLElement>\(MOBILE_DIALOG_FOCUSABLE_SELECTOR\)/)
assert.match(page, /querySelectorAll<HTMLElement>\(MOBILE_DIALOG_FOCUSABLE_SELECTOR\)/)
assert.match(page, /matchMedia\('\(min-width: 769px\)'\)[\s\S]*messagesEndRef\.current\?\.scrollIntoView/)
assert.match(page, /message\.result && hasGuideRecommendations\(message\.result\)/)
assert.doesNotMatch(page, /查看全部/)
assert.doesNotMatch(page, /MOBILE_LIVE_QUICK_QUESTIONS/)
assert.doesNotMatch(page, /className="digital-mobile-quick-questions"/)
assert.doesNotMatch(mobileLive, /MOBILE_LIVE_COMMENT_LIMIT/)
assert.doesNotMatch(mobileLive, /\.slice\(/)
assert.match(page, /className="digital-human-chat"/, 'desktop chat remains rendered')
assert.doesNotMatch(page, /data-mobile-hidden-on-short/)
assert.doesNotMatch(styles, /-webkit-line-clamp/)
assert.match(styles, /\.digital-mobile-comment-feed\s*\{[^}]*overflow-x:\s*hidden;[^}]*overflow-y:\s*auto;/s)
assert.match(styles, /\.digital-mobile-comment > span\s*\{[^}]*white-space:\s*normal;[^}]*overflow-wrap:\s*anywhere;/s)
assert.doesNotMatch(styles, /\.digital-mobile-comment:nth-of-type\(-n\+2\)/)
console.log('mobile digital-human live interaction contract passed')
