import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')
const page = read('./LiveBroadcastPage.tsx')
const css = read('./LiveBroadcastPage.css')
const app = read('../App.tsx')
const appCss = read('../App.css')
const runtime = read('../live/liveBroadcastRuntime.ts')
const liveApi = read('../api/liveBroadcast.ts')

assert.match(app, /path="\/live"[\s\S]*<LiveBroadcastPage/)
assert.match(app, /<Route element=\{<ProtectedRoute/)
assert.match(page, /getLiveStatus\(\{ signal:/)
assert.match(liveApi, /items:\s*LiveTimelineItem\[\]/)
assert.doesNotMatch(liveApi, /\{\s*id,\s*\.\.\.item\s*\}/)
assert.match(page, /resolveCurrentLivePosition\(snapshot,/)
assert.doesNotMatch(page, /resolveLivePosition\([^,]+,\s*Date\.now\(\)/)
assert.match(page, /visibilitychange/)
assert.match(page, /syncLiveStatus\('visibility-resume'\)/)
assert.match(page, /LIVE_STATUS_POLL_INTERVAL_MS\s*=\s*30_000/)
assert.match(page, /document\.visibilityState === 'visible'[\s\S]*syncLiveStatus\('poll'\)/)
assert.match(page, /window\.clearInterval\(pollTimer\)/)
assert.match(page, /syncRequestRef\.current\?\.abort\(\)/)
assert.match(page, /stopPlayback\(\)[\s\S]*setPhase\('asking'\)/)
assert.match(page, /syncLiveStatus\('answer-complete'\)/)
assert.match(page, /spokenItemRef\.current = null[\s\S]*getLiveStatus/)
assert.match(page, /finally\s*\{[\s\S]*syncLiveStatus\('answer-complete'\)/)
assert.match(page, /signal\.addEventListener\('abort'/)
assert.match(page, /parseLiveGuideStreamData\(raw\)/)
assert.match(runtime, /data\.error[\s\S]*throw new Error/)
assert.match(page, /if \(!fullAnswer\.trim\(\)\) throw new Error/)
assert.match(page, /phase === 'syncing' \|\| phase === 'resuming' \? '重连中'[\s\S]*snapshot\?\.status === 'live' \? '直播中'/)
assert.match(page, /speak\(model, audioUrl/)
assert.match(page, /recognitionRef\.current\?\.abort\?\.\(\)/)
assert.match(page, /mountedRef\.current[\s\S]*recognitionGenerationRef\.current === generation/)
assert.match(page, /try\s*\{\s*recognition\.start\(\)[\s\S]*catch[\s\S]*语音识别启动失败/)
assert.match(page, /interactionError[\s\S]*role="alert"/)
assert.match(page, /syncError[\s\S]*role="status"/)
assert.match(page, /onClick=\{\(\) => void syncLiveStatus\('retry'\)\}[\s\S]*重新连接/)
assert.match(page, /const isInteractionBusy = \['syncing', 'asking', 'answering', 'resuming'\]\.includes\(phase\)/)
assert.match(page, /disabled=\{!draft\.trim\(\) \|\| isInteractionBusy\}/)
assert.doesNotMatch(page, /setCurrentItemIndex\(/)
assert.match(page, /versionRef\.current !== snapshot\.versionId[\s\S]*stopPlayback\(\)/)
assert.match(page, /const previousSnapshot = snapshotRef\.current/)
assert.match(page, /shouldSkipBackgroundLiveSync\(reason, interactionRequestRef\.current !== null, activeSyncReasonRef\.current\)\) return/)
assert.match(page, /shouldDiscardBackgroundLiveSyncResult\(reason, interactionRequestRef\.current !== null\)\) return[\s\S]*applySnapshot\(snapshot\)/)
assert.match(page, /catch \(syncError\)[\s\S]*shouldDiscardBackgroundLiveSyncResult\(reason, interactionRequestRef\.current !== null\)\) return[\s\S]*setSyncError/)
assert.match(page, /activeSyncReasonRef\.current === 'poll' \|\| activeSyncReasonRef\.current === 'visibility-resume'[\s\S]*syncRequestRef\.current\?\.abort\(\)[\s\S]*stopPlayback\(\)/)
assert.match(page, /shouldRecoverLiveSpeechAfterSyncFailure\(reason, previousSnapshot\?\.status === 'live'\)[\s\S]*spokenItemRef\.current = null[\s\S]*setPosition\(resolveCurrentLivePosition\(previousSnapshot, Date\.now\(\)\)\)[\s\S]*setPhase\('broadcasting'\)/)
assert.doesNotMatch(page, /if \(previousSnapshot\?\.status === 'live'\) \{\s*spokenItemRef\.current = null/)
assert.match(page, /直播语音播放失败[\s\S]*console\.warn/)
assert.match(page, /const \[broadcastSpeechError, setBroadcastSpeechError\]/)
assert.match(page, /setBroadcastSpeechError\(''\)[\s\S]*playText\(position\.item\.content/)
assert.doesNotMatch(page, /spokenItemRef\.current = speechKey\s*setInteractionError\(''\)/)
assert.match(page, /broadcastSpeechError[\s\S]*role="status"/)
assert.match(page, /AbortController/)
assert.match(page, /直播内容准备中/)
assert.match(page, /停止本地回答/)
assert.match(page, /语音提问/)
assert.match(css, /\.live-broadcast-page\s*\{[^}]*touch-action:\s*pan-y/s)
assert.match(css, /\.live-broadcast-page\s*,\s*\.live-broadcast-page\s+\*\s*\{[^}]*box-sizing:\s*border-box/s)
assert.match(css, /\.live-stage__canvas\s*\{[^}]*touch-action:\s*none/s)
assert.match(css, /@media\s*\(max-width:\s*768px\)[\s\S]*\.live-broadcast-page__body\s*\{[^}]*grid-template-columns:\s*1fr/s)
assert.doesNotMatch(css, /padding-bottom:\s*calc\(var\(--mobile-nav-height\)/)
assert.match(appCss, /\.authenticated-app__content\s*\{[^}]*padding-bottom:\s*calc\(var\(--mobile-nav-height\) \+ var\(--safe-bottom\) \+ 16px\)/s)

console.log('live broadcast page contract passed')
