import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')
const page = read('./LiveBroadcastPage.tsx')
const app = read('../App.tsx')
const runtime = read('../live/liveBroadcastRuntime.ts')
const liveApi = read('../api/liveBroadcast.ts')

assert.match(app, /path="\/live"[\s\S]*<LiveBroadcastPage/)
assert.match(app, /<Route element=\{<ProtectedRoute/)
assert.match(liveApi, /getFacilityLiveConfig/)
assert.match(liveApi, /params:\s*\{ facilityId \}/)
assert.match(liveApi, /export type FacilityLiveNarration/)
assert.match(liveApi, /narration\?: FacilityLiveNarration \| null/)
assert.match(page, /searchParams\.get\('spotId'\)/)
assert.match(page, /getFacilityLiveConfig\(facilityId/)
assert.match(page, /digitalHuman\.modelPath/)
assert.match(page, /liveConfig\?\.liveSourceType === 'video'/)
assert.match(page, /<video[\s\S]*className="live-stage__media"[\s\S]*src=\{liveConfig\.liveVideoUrl \?\? undefined\}[\s\S]*autoPlay[\s\S]*muted[\s\S]*loop[\s\S]*playsInline/)
assert.match(page, /onCanPlay=\{\(\) => setMediaReady\(true\)\}/)
assert.match(page, /onError=\{\(\) => setMediaError\('直播视频加载失败，请检查视频地址或重新上传。'\)\}/)
assert.doesNotMatch(page, /MODEL_OPTIONS\[0\]/)
assert.match(page, /createNarrationController/)
assert.match(page, /appendLiveMessage/)
assert.match(page, /updateLiveMessage/)
assert.match(page, /type LiveChatMessage/)
assert.match(page, /liveConfig\.narration\?\.audioUrl/)
assert.match(page, /const narrationAudioUrl = liveConfig\.narration\.audioUrl/)
assert.match(page, /narrationControllerRef\.current\?\.start\(narrationAudioUrl\)/)
assert.match(page, /narrationControllerRef\.current\?\.interrupt\(\)[\s\S]*setPhase\('asking'\)/)
assert.match(page, /appendLiveMessage\(previous, viewerMessage\)/)
assert.match(page, /appendLiveMessage\([^\n]+hostMessage\)/)
assert.match(page, /updateLiveMessage\([^\n]+hostMessage\.id,[\s\S]*content: fullAnswer[\s\S]*status: 'streaming'/)
assert.match(page, /updateLiveMessage\([^\n]+hostMessage\.id,[\s\S]*status: 'sent'/)
assert.match(page, /if \(liveConfig\?\.narration\?\.audioUrl\) \{[\s\S]*setPhase\('resume-wait'\)[\s\S]*narrationControllerRef\.current\?\.resume\(\)/)
assert.match(page, /await playText\(fullAnswer, controller\.signal\)/)
assert.doesNotMatch(page, /getLiveStatus/)
assert.doesNotMatch(page, /LivePosition/)
assert.doesNotMatch(page, /resolveCurrentLivePosition/)
assert.doesNotMatch(page, /LIVE_STATUS_POLL_INTERVAL_MS/)
assert.doesNotMatch(page, /\/api\/user\/live\/status/)
assert.match(page, /parseLiveGuideStreamData\(raw\)/)
assert.match(runtime, /data\.error[\s\S]*throw new Error/)
assert.match(page, /if \(!fullAnswer\.trim\(\)\) throw new Error/)
assert.match(page, /speak\(model, audioUrl/)
assert.match(page, /interactionError[\s\S]*role="alert"/)
assert.match(page, /broadcastSpeechError[\s\S]*role="status"/)
assert.match(page, /AbortController/)
assert.match(page, /直播内容准备中/)
assert.doesNotMatch(page, /停止本地回答/)
assert.doesNotMatch(page, /语音提问/)

console.log('live broadcast page contract passed')
