import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const page = readFileSync(new URL('MapPage.tsx', import.meta.url), 'utf8')
const css = readFileSync(new URL('MapPage.css', import.meta.url), 'utf8')
const mapMobile = css.slice(css.indexOf('@media (max-width: 768px)'))

assert.match(page, /const \[mobileDrawerState, setMobileDrawerState\] = useState<MobileMapDrawerState>\('collapsed'\)/)
assert.match(page, /const \[mobileCategoryOpen, setMobileCategoryOpen\] = useState\(false\)/)
assert.match(page, /<main className="page-shell page-shell--map">/)
assert.match(page, /<section className="page-content page-content--map">/)
assert.match(page, /className="map-mobile-toolbar"/)
assert.match(page, /className="map-mobile-context-actions"/)
assert.match(page, /className={`map-mobile-drawer map-mobile-drawer--\$\{mobileDrawerState\}`}/)
assert.match(page, /role="dialog"[\s\S]*aria-modal="true"[\s\S]*aria-labelledby="mobile-map-drawer-title"/)
assert.match(page, /event\.key === 'Escape'/)
assert.match(page, /mobileDrawerTriggerRef\.current\?\.focus\(\)/)
assert.match(page, /isolateMobileMapDialogBackground/)
assert.match(page, /window\.matchMedia\(MOBILE_MAP_WORKBENCH_MEDIA_QUERY\)/)
assert.match(page, /watchMobileMapWorkbenchViewport\(mediaQuery, collapseMobileDrawer\)/)
assert.match(page, /\.visitor-topbar'[\s\S]*\.map-page__main'[\s\S]*\.map-side'[\s\S]*\.mobile-bottom-nav'/)
assert.match(page, /document\.addEventListener\('focusin'/)
assert.match(page, /panel\.contains\(event\.target as Node\)/)
assert.match(page, /function clearSearchResults\(\)/)
assert.match(page, /createMobileMapSearchDerivedSelection\(\)/)
assert.match(page, /function clearSearchDerivedSelection\(\)[\s\S]*searchDerivedSelectionRef\.current\.beginSearch\(\)[\s\S]*setSelectedFacility\(null\)[\s\S]*setCardPosition\(null\)/)
assert.ok((page.match(/clearSearchDerivedSelection\(\)/g) ?? []).length >= 3, 'clear and every valid search share one derived-selection reset')
assert.match(page, /setSearchResultCount\(1\)/)
assert.match(page, /shouldShowMobileMapClearAction\(searchResultCount\)/)
assert.match(page, /const handleSearch = \(\) => \{[\s\S]*removeSearchMarkers\(\)[\s\S]*setSearchResultCount\(1\)[\s\S]*if \(!pois\.length\) \{\s*return\s*\}/)
assert.match(page, /createMobileMapSearchGenerationGate\(\)/)
assert.match(page, /const searchGeneration = searchGenerationGateRef\.current\.begin\(\)/)
assert.match(page, /searchGenerationGateRef\.current\.isCurrent\(searchGeneration\)/)
assert.match(page, /function removeSearchMarkers\(\)/)
assert.match(page, /function renderLiveCard\(\) \{[\s\S]*if \(!selectedFacility\) \{[\s\S]*return null[\s\S]*\}/)
assert.match(page, /const liveRoute = selectedFacilityQuery \? `\/live\?\$\{selectedFacilityQuery\}` : '\/live'/)
assert.match(page, /const digitalHumanRoute = selectedFacilityQuery[\s\S]*\? `\$\{DIGITAL_HUMAN_ROUTE\}\?\$\{selectedFacilityQuery\}`[\s\S]*: DIGITAL_HUMAN_ROUTE/)
assert.match(page, /navigate\(liveRoute\)/)
assert.match(page, /navigate\(digitalHumanRoute\)/)
assert.match(page, /const nearbyServiceCategories = categories\.slice\(0, 5\)/)
assert.match(page, /nearbyServiceCategories\.map\(\(category, index\)/)
assert.match(page, /onClick=\{\(\) => setActiveCategory\(categoryKey\)\}/)
assert.doesNotMatch(page, /<span>停车场<\/span>[\s\S]*<span>卫生间<\/span>[\s\S]*<span>餐饮<\/span>/)

assert.match(mapMobile, /\.authenticated-app__content\s*>\s*\.page-shell--map\s*\{[^}]*height:\s*100%[^}]*min-height:\s*0[^}]*overflow:\s*hidden[^}]*padding:\s*0/s)
assert.match(mapMobile, /\.page-shell--map\s*>\s*\.page-content--map\s*\{[^}]*flex:\s*1[^}]*min-height:\s*0[^}]*overflow:\s*hidden/s)
assert.match(mapMobile, /\.map-page\s*\{[^}]*height:\s*100%[^}]*overflow:\s*hidden/s)
assert.match(mapMobile, /\.map-page__main\s*\{[^}]*height:\s*100%[^}]*min-height:\s*0/s)
assert.match(mapMobile, /\.map-sidebar,[\s\S]*\.map-search,[\s\S]*\.map-actions,[\s\S]*\.map-side\s*\{[^}]*display:\s*none/s)
assert.match(mapMobile, /\.map-page\s*\{[^}]*--map-mobile-bottom-offset:\s*calc\(var\(--mobile-nav-height\)\s*\+\s*var\(--safe-bottom\)\)/s)
assert.match(mapMobile, /\.map-mobile-drawer\s*\{[^}]*position:\s*fixed[^}]*bottom:\s*calc\(var\(--map-mobile-bottom-offset\)\s*\+\s*8px\)/s)
assert.match(mapMobile, /\.map-mobile-drawer--expanded\s*>\s*button\s*\{[^}]*display:\s*none/s)
assert.match(mapMobile, /\.map-mobile-drawer__panel\s*\{[^}]*max-height:\s*min\(72dvh,\s*620px\)[^}]*overflow-y:\s*auto/s)
assert.match(mapMobile, /\.map-spot-card\s*\{[^}]*bottom:\s*calc\(var\(--map-mobile-bottom-offset\)[^}]*var\(--map-mobile-drawer-peek-height\)/s)
assert.match(mapMobile, /\.map-mobile-drawer__panel\s+\.live-card__msg:nth-child\(-n\s*\+\s*2\)\s*\{[^}]*display:\s*none/s)
assert.doesNotMatch(mapMobile, /(?<!\.map-mobile-drawer__panel\s)\.live-card__msg:nth-child\(-n\s*\+\s*2\)/s)
assert.match(page, /className="map-mobile-drawer__drag-handle"/)
assert.match(page, />\s*\u5c55\u5f00\s*</)
assert.match(page, />\s*\u6536\u8d77\s*</)
assert.match(page, /onPointerDown=/)
assert.match(page, /onPointerUp=/)
assert.match(css, /@media\s*\(max-width:\s*768px\),\s*\(max-width:\s*932px\)\s*and\s*\(max-height:\s*520px\)\s*and\s*\(orientation:\s*landscape\)/s)
assert.match(css, /\.map-mobile-drawer--expanded\s*\{[^}]*z-index:\s*1100/s)
assert.match(css, /\.map-mobile-drawer__drag-handle\s*\{[^}]*min-height:\s*var\(--touch-target\)/s)

console.log('MapPage mobile workbench source contract passed')
